{% set name = "napari-nlm" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-nlm-{{ version }}.tar.gz
  sha256: 7ddb0cf593f99b79fdcbe050f4fb4d5a1ade61d1ef4444397c9418415ec2d191

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - gputools
    - magicgui
    - napari
    - numpy <1.24
    - pyopencl
    - python >=3.8
    - qtpy
    - scikit-image

test:
  imports:
    - napari_nlm
  commands:
    - pip list
    # - pip check  # Fails due to pin on pyopencl. Remove on following package update
  requires:
    - oclgrind
    - pip

about:
  home: https://github.com/maweigert/napari-nlm
  summary: NLM (non local means) denoising
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - maweigert
